/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PsyRouteImport } from './routes/psy'
import { Route as PiesIdRouteImport } from './routes/pies.$id'
import { Route as PiesIdKalendarzRouteImport } from './routes/pies.$id.kalendarz'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PsyRoute = PsyRouteImport.update({
  id: '/psy',
  path: '/psy',
  getParentRoute: () => rootRouteImport,
} as any)
const PiesIdRoute = PiesIdRouteImport.update({
  id: '/pies/$id',
  path: '/pies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PiesIdKalendarzRoute = PiesIdKalendarzRouteImport.update({
  id: '/kalendarz',
  path: '/kalendarz',
  getParentRoute: () => PiesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/psy': typeof PsyRoute
  '/pies/$id': typeof PiesIdRouteWithChildren
  '/pies/$id/kalendarz': typeof PiesIdKalendarzRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/psy': typeof PsyRoute
  '/pies/$id': typeof PiesIdRouteWithChildren
  '/pies/$id/kalendarz': typeof PiesIdKalendarzRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/psy': typeof PsyRoute
  '/pies/$id': typeof PiesIdRouteWithChildren
  '/pies/$id/kalendarz': typeof PiesIdKalendarzRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/psy' | '/pies/$id' | '/pies/$id/kalendarz'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/psy' | '/pies/$id' | '/pies/$id/kalendarz'
  id: '__root__' | '/' | '/psy' | '/pies/$id' | '/pies/$id/kalendarz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PsyRoute: typeof PsyRoute
  PiesIdRoute: typeof PiesIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psy': {
      id: '/psy'
      path: '/psy'
      fullPath: '/psy'
      preLoaderRoute: typeof PsyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pies/$id': {
      id: '/pies/$id'
      path: '/pies/$id'
      fullPath: '/pies/$id'
      preLoaderRoute: typeof PiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pies/$id/kalendarz': {
      id: '/pies/$id/kalendarz'
      path: '/kalendarz'
      fullPath: '/pies/$id/kalendarz'
      preLoaderRoute: typeof PiesIdKalendarzRouteImport
      parentRoute: typeof PiesIdRoute
    }
  }
}

interface PiesIdRouteChildren {
  PiesIdKalendarzRoute: typeof PiesIdKalendarzRoute
}

const PiesIdRouteChildren: PiesIdRouteChildren = {
  PiesIdKalendarzRoute: PiesIdKalendarzRoute,
}

const PiesIdRouteWithChildren =
  PiesIdRoute._addFileChildren(PiesIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PsyRoute: PsyRoute,
  PiesIdRoute: PiesIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
