/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedPsyRouteImport } from './routes/_authenticated/psy'
import { Route as AuthenticatedPiesIdRouteImport } from './routes/_authenticated/pies.$id'
import { Route as AuthenticatedPiesIdIndexRouteImport } from './routes/_authenticated/pies.$id.index'
import { Route as AuthenticatedPiesIdAnalizaRouteImport } from './routes/_authenticated/pies.$id.analiza'
import { Route as AuthenticatedPiesIdKalendarzRouteImport } from './routes/_authenticated/pies.$id.kalendarz'
import { Route as AuthenticatedPiesIdTabelaRouteImport } from './routes/_authenticated/pies.$id.tabela'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPsyRoute = AuthenticatedPsyRouteImport.update({
  id: '/psy',
  path: '/psy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPiesIdRoute = AuthenticatedPiesIdRouteImport.update({
  id: '/pies/$id',
  path: '/pies/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPiesIdIndexRoute =
  AuthenticatedPiesIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPiesIdRoute,
  } as any)
const AuthenticatedPiesIdAnalizaRoute =
  AuthenticatedPiesIdAnalizaRouteImport.update({
    id: '/analiza',
    path: '/analiza',
    getParentRoute: () => AuthenticatedPiesIdRoute,
  } as any)
const AuthenticatedPiesIdKalendarzRoute =
  AuthenticatedPiesIdKalendarzRouteImport.update({
    id: '/kalendarz',
    path: '/kalendarz',
    getParentRoute: () => AuthenticatedPiesIdRoute,
  } as any)
const AuthenticatedPiesIdTabelaRoute =
  AuthenticatedPiesIdTabelaRouteImport.update({
    id: '/tabela',
    path: '/tabela',
    getParentRoute: () => AuthenticatedPiesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/psy': typeof AuthenticatedPsyRoute
  '/pies/$id': typeof AuthenticatedPiesIdRouteWithChildren
  '/pies/$id/analiza': typeof AuthenticatedPiesIdAnalizaRoute
  '/pies/$id/kalendarz': typeof AuthenticatedPiesIdKalendarzRoute
  '/pies/$id/tabela': typeof AuthenticatedPiesIdTabelaRoute
  '/pies/$id/': typeof AuthenticatedPiesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/psy': typeof AuthenticatedPsyRoute
  '/pies/$id/analiza': typeof AuthenticatedPiesIdAnalizaRoute
  '/pies/$id/kalendarz': typeof AuthenticatedPiesIdKalendarzRoute
  '/pies/$id/tabela': typeof AuthenticatedPiesIdTabelaRoute
  '/pies/$id': typeof AuthenticatedPiesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/psy': typeof AuthenticatedPsyRoute
  '/_authenticated/pies/$id': typeof AuthenticatedPiesIdRouteWithChildren
  '/_authenticated/pies/$id/analiza': typeof AuthenticatedPiesIdAnalizaRoute
  '/_authenticated/pies/$id/kalendarz': typeof AuthenticatedPiesIdKalendarzRoute
  '/_authenticated/pies/$id/tabela': typeof AuthenticatedPiesIdTabelaRoute
  '/_authenticated/pies/$id/': typeof AuthenticatedPiesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/psy'
    | '/pies/$id'
    | '/pies/$id/analiza'
    | '/pies/$id/kalendarz'
    | '/pies/$id/tabela'
    | '/pies/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/psy'
    | '/pies/$id/analiza'
    | '/pies/$id/kalendarz'
    | '/pies/$id/tabela'
    | '/pies/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/psy'
    | '/_authenticated/pies/$id'
    | '/_authenticated/pies/$id/analiza'
    | '/_authenticated/pies/$id/kalendarz'
    | '/_authenticated/pies/$id/tabela'
    | '/_authenticated/pies/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/psy': {
      id: '/_authenticated/psy'
      path: '/psy'
      fullPath: '/psy'
      preLoaderRoute: typeof AuthenticatedPsyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pies/$id': {
      id: '/_authenticated/pies/$id'
      path: '/pies/$id'
      fullPath: '/pies/$id'
      preLoaderRoute: typeof AuthenticatedPiesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pies/$id/': {
      id: '/_authenticated/pies/$id/'
      path: '/'
      fullPath: '/pies/$id/'
      preLoaderRoute: typeof AuthenticatedPiesIdIndexRouteImport
      parentRoute: typeof AuthenticatedPiesIdRoute
    }
    '/_authenticated/pies/$id/analiza': {
      id: '/_authenticated/pies/$id/analiza'
      path: '/analiza'
      fullPath: '/pies/$id/analiza'
      preLoaderRoute: typeof AuthenticatedPiesIdAnalizaRouteImport
      parentRoute: typeof AuthenticatedPiesIdRoute
    }
    '/_authenticated/pies/$id/kalendarz': {
      id: '/_authenticated/pies/$id/kalendarz'
      path: '/kalendarz'
      fullPath: '/pies/$id/kalendarz'
      preLoaderRoute: typeof AuthenticatedPiesIdKalendarzRouteImport
      parentRoute: typeof AuthenticatedPiesIdRoute
    }
    '/_authenticated/pies/$id/tabela': {
      id: '/_authenticated/pies/$id/tabela'
      path: '/tabela'
      fullPath: '/pies/$id/tabela'
      preLoaderRoute: typeof AuthenticatedPiesIdTabelaRouteImport
      parentRoute: typeof AuthenticatedPiesIdRoute
    }
  }
}

interface AuthenticatedPiesIdRouteChildren {
  AuthenticatedPiesIdAnalizaRoute: typeof AuthenticatedPiesIdAnalizaRoute
  AuthenticatedPiesIdKalendarzRoute: typeof AuthenticatedPiesIdKalendarzRoute
  AuthenticatedPiesIdTabelaRoute: typeof AuthenticatedPiesIdTabelaRoute
  AuthenticatedPiesIdIndexRoute: typeof AuthenticatedPiesIdIndexRoute
}

const AuthenticatedPiesIdRouteChildren: AuthenticatedPiesIdRouteChildren = {
  AuthenticatedPiesIdAnalizaRoute: AuthenticatedPiesIdAnalizaRoute,
  AuthenticatedPiesIdKalendarzRoute: AuthenticatedPiesIdKalendarzRoute,
  AuthenticatedPiesIdTabelaRoute: AuthenticatedPiesIdTabelaRoute,
  AuthenticatedPiesIdIndexRoute: AuthenticatedPiesIdIndexRoute,
}

const AuthenticatedPiesIdRouteWithChildren =
  AuthenticatedPiesIdRoute._addFileChildren(AuthenticatedPiesIdRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPsyRoute: typeof AuthenticatedPsyRoute
  AuthenticatedPiesIdRoute: typeof AuthenticatedPiesIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPsyRoute: AuthenticatedPsyRoute,
  AuthenticatedPiesIdRoute: AuthenticatedPiesIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
