/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as PrywatnoscRouteImport } from './routes/prywatnosc'
import { Route as RegulaminRouteImport } from './routes/regulamin'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedPsyRouteImport } from './routes/_authenticated/psy'
import { Route as AuthenticatedPiesIdRouteImport } from './routes/_authenticated/pies.$id'
import { Route as AuthenticatedPiesIdIndexRouteImport } from './routes/_authenticated/pies.$id.index'
import { Route as AuthenticatedPiesIdAnalizaRouteImport } from './routes/_authenticated/pies.$id.analiza'
import { Route as AuthenticatedPiesIdKalendarzRouteImport } from './routes/_authenticated/pies.$id.kalendarz'
import { Route as AuthenticatedPiesIdTabelaRouteImport } from './routes/_authenticated/pies.$id.tabela'
import { Route as AuthenticatedPiesIdZaleceniaRouteImport } from './routes/_authenticated/pies.$id.zalecenia'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as AuthenticatedPiesIdWydarzenieEntryIdRouteImport } from './routes/_authenticated/pies.$id.wydarzenie.$entryId'
import { Route as AuthenticatedPiesIdWydarzenieNoweRouteImport } from './routes/_authenticated/pies.$id.wydarzenie.nowe'
import { Route as AuthenticatedPiesIdWydarzenieEntryIdEdytujRouteImport } from './routes/_authenticated/pies.$id.wydarzenie.$entryId.edytuj'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrywatnoscRoute = PrywatnoscRouteImport.update({
  id: '/prywatnosc',
  path: '/prywatnosc',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulaminRoute = RegulaminRouteImport.update({
  id: '/regulamin',
  path: '/regulamin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPsyRoute = AuthenticatedPsyRouteImport.update({
  id: '/psy',
  path: '/psy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPiesIdRoute = AuthenticatedPiesIdRouteImport.update({
  id: '/pies/$id',
  path: '/pies/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPiesIdIndexRoute =
  AuthenticatedPiesIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPiesIdRoute,
  } as any)
const AuthenticatedPiesIdAnalizaRoute =
  AuthenticatedPiesIdAnalizaRouteImport.update({
    id: '/analiza',
    path: '/analiza',
    getParentRoute: () => AuthenticatedPiesIdRoute,
  } as any)
const AuthenticatedPiesIdKalendarzRoute =
  AuthenticatedPiesIdKalendarzRouteImport.update({
    id: '/kalendarz',
    path: '/kalendarz',
    getParentRoute: () => AuthenticatedPiesIdRoute,
  } as any)
const AuthenticatedPiesIdTabelaRoute =
  AuthenticatedPiesIdTabelaRouteImport.update({
    id: '/tabela',
    path: '/tabela',
    getParentRoute: () => AuthenticatedPiesIdRoute,
  } as any)
const AuthenticatedPiesIdZaleceniaRoute =
  AuthenticatedPiesIdZaleceniaRouteImport.update({
    id: '/zalecenia',
    path: '/zalecenia',
    getParentRoute: () => AuthenticatedPiesIdRoute,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPiesIdWydarzenieEntryIdRoute =
  AuthenticatedPiesIdWydarzenieEntryIdRouteImport.update({
    id: '/wydarzenie/$entryId',
    path: '/wydarzenie/$entryId',
    getParentRoute: () => AuthenticatedPiesIdRoute,
  } as any)
const AuthenticatedPiesIdWydarzenieNoweRoute =
  AuthenticatedPiesIdWydarzenieNoweRouteImport.update({
    id: '/wydarzenie/nowe',
    path: '/wydarzenie/nowe',
    getParentRoute: () => AuthenticatedPiesIdRoute,
  } as any)
const AuthenticatedPiesIdWydarzenieEntryIdEdytujRoute =
  AuthenticatedPiesIdWydarzenieEntryIdEdytujRouteImport.update({
    id: '/edytuj',
    path: '/edytuj',
    getParentRoute: () => AuthenticatedPiesIdWydarzenieEntryIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kontakt': typeof KontaktRoute
  '/prywatnosc': typeof PrywatnoscRoute
  '/regulamin': typeof RegulaminRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/psy': typeof AuthenticatedPsyRoute
  '/pies/$id': typeof AuthenticatedPiesIdRouteWithChildren
  '/pies/$id/analiza': typeof AuthenticatedPiesIdAnalizaRoute
  '/pies/$id/kalendarz': typeof AuthenticatedPiesIdKalendarzRoute
  '/pies/$id/tabela': typeof AuthenticatedPiesIdTabelaRoute
  '/pies/$id/zalecenia': typeof AuthenticatedPiesIdZaleceniaRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/pies/$id/': typeof AuthenticatedPiesIdIndexRoute
  '/pies/$id/wydarzenie/$entryId': typeof AuthenticatedPiesIdWydarzenieEntryIdRouteWithChildren
  '/pies/$id/wydarzenie/nowe': typeof AuthenticatedPiesIdWydarzenieNoweRoute
  '/pies/$id/wydarzenie/$entryId/edytuj': typeof AuthenticatedPiesIdWydarzenieEntryIdEdytujRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kontakt': typeof KontaktRoute
  '/prywatnosc': typeof PrywatnoscRoute
  '/regulamin': typeof RegulaminRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/psy': typeof AuthenticatedPsyRoute
  '/pies/$id/analiza': typeof AuthenticatedPiesIdAnalizaRoute
  '/pies/$id/kalendarz': typeof AuthenticatedPiesIdKalendarzRoute
  '/pies/$id/tabela': typeof AuthenticatedPiesIdTabelaRoute
  '/pies/$id/zalecenia': typeof AuthenticatedPiesIdZaleceniaRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/pies/$id': typeof AuthenticatedPiesIdIndexRoute
  '/pies/$id/wydarzenie/$entryId': typeof AuthenticatedPiesIdWydarzenieEntryIdRouteWithChildren
  '/pies/$id/wydarzenie/nowe': typeof AuthenticatedPiesIdWydarzenieNoweRoute
  '/pies/$id/wydarzenie/$entryId/edytuj': typeof AuthenticatedPiesIdWydarzenieEntryIdEdytujRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/kontakt': typeof KontaktRoute
  '/prywatnosc': typeof PrywatnoscRoute
  '/regulamin': typeof RegulaminRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/psy': typeof AuthenticatedPsyRoute
  '/_authenticated/pies/$id': typeof AuthenticatedPiesIdRouteWithChildren
  '/_authenticated/pies/$id/analiza': typeof AuthenticatedPiesIdAnalizaRoute
  '/_authenticated/pies/$id/kalendarz': typeof AuthenticatedPiesIdKalendarzRoute
  '/_authenticated/pies/$id/tabela': typeof AuthenticatedPiesIdTabelaRoute
  '/_authenticated/pies/$id/zalecenia': typeof AuthenticatedPiesIdZaleceniaRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/_authenticated/pies/$id/': typeof AuthenticatedPiesIdIndexRoute
  '/_authenticated/pies/$id/wydarzenie/$entryId': typeof AuthenticatedPiesIdWydarzenieEntryIdRouteWithChildren
  '/_authenticated/pies/$id/wydarzenie/nowe': typeof AuthenticatedPiesIdWydarzenieNoweRoute
  '/_authenticated/pies/$id/wydarzenie/$entryId/edytuj': typeof AuthenticatedPiesIdWydarzenieEntryIdEdytujRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/kontakt'
    | '/prywatnosc'
    | '/regulamin'
    | '/profil'
    | '/psy'
    | '/pies/$id'
    | '/pies/$id/analiza'
    | '/pies/$id/kalendarz'
    | '/pies/$id/tabela'
    | '/pies/$id/zalecenia'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/pies/$id/'
    | '/pies/$id/wydarzenie/$entryId'
    | '/pies/$id/wydarzenie/nowe'
    | '/pies/$id/wydarzenie/$entryId/edytuj'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/kontakt'
    | '/prywatnosc'
    | '/regulamin'
    | '/profil'
    | '/psy'
    | '/pies/$id/analiza'
    | '/pies/$id/kalendarz'
    | '/pies/$id/tabela'
    | '/pies/$id/zalecenia'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/pies/$id'
    | '/pies/$id/wydarzenie/$entryId'
    | '/pies/$id/wydarzenie/nowe'
    | '/pies/$id/wydarzenie/$entryId/edytuj'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/kontakt'
    | '/prywatnosc'
    | '/regulamin'
    | '/_authenticated/profil'
    | '/_authenticated/psy'
    | '/_authenticated/pies/$id'
    | '/_authenticated/pies/$id/analiza'
    | '/_authenticated/pies/$id/kalendarz'
    | '/_authenticated/pies/$id/tabela'
    | '/_authenticated/pies/$id/zalecenia'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/_authenticated/pies/$id/'
    | '/_authenticated/pies/$id/wydarzenie/$entryId'
    | '/_authenticated/pies/$id/wydarzenie/nowe'
    | '/_authenticated/pies/$id/wydarzenie/$entryId/edytuj'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  KontaktRoute: typeof KontaktRoute
  PrywatnoscRoute: typeof PrywatnoscRoute
  RegulaminRoute: typeof RegulaminRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prywatnosc': {
      id: '/prywatnosc'
      path: '/prywatnosc'
      fullPath: '/prywatnosc'
      preLoaderRoute: typeof PrywatnoscRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulamin': {
      id: '/regulamin'
      path: '/regulamin'
      fullPath: '/regulamin'
      preLoaderRoute: typeof RegulaminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/psy': {
      id: '/_authenticated/psy'
      path: '/psy'
      fullPath: '/psy'
      preLoaderRoute: typeof AuthenticatedPsyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pies/$id': {
      id: '/_authenticated/pies/$id'
      path: '/pies/$id'
      fullPath: '/pies/$id'
      preLoaderRoute: typeof AuthenticatedPiesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pies/$id/': {
      id: '/_authenticated/pies/$id/'
      path: '/'
      fullPath: '/pies/$id/'
      preLoaderRoute: typeof AuthenticatedPiesIdIndexRouteImport
      parentRoute: typeof AuthenticatedPiesIdRoute
    }
    '/_authenticated/pies/$id/analiza': {
      id: '/_authenticated/pies/$id/analiza'
      path: '/analiza'
      fullPath: '/pies/$id/analiza'
      preLoaderRoute: typeof AuthenticatedPiesIdAnalizaRouteImport
      parentRoute: typeof AuthenticatedPiesIdRoute
    }
    '/_authenticated/pies/$id/kalendarz': {
      id: '/_authenticated/pies/$id/kalendarz'
      path: '/kalendarz'
      fullPath: '/pies/$id/kalendarz'
      preLoaderRoute: typeof AuthenticatedPiesIdKalendarzRouteImport
      parentRoute: typeof AuthenticatedPiesIdRoute
    }
    '/_authenticated/pies/$id/tabela': {
      id: '/_authenticated/pies/$id/tabela'
      path: '/tabela'
      fullPath: '/pies/$id/tabela'
      preLoaderRoute: typeof AuthenticatedPiesIdTabelaRouteImport
      parentRoute: typeof AuthenticatedPiesIdRoute
    }
    '/_authenticated/pies/$id/zalecenia': {
      id: '/_authenticated/pies/$id/zalecenia'
      path: '/zalecenia'
      fullPath: '/pies/$id/zalecenia'
      preLoaderRoute: typeof AuthenticatedPiesIdZaleceniaRouteImport
      parentRoute: typeof AuthenticatedPiesIdRoute
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pies/$id/wydarzenie/$entryId': {
      id: '/_authenticated/pies/$id/wydarzenie/$entryId'
      path: '/wydarzenie/$entryId'
      fullPath: '/pies/$id/wydarzenie/$entryId'
      preLoaderRoute: typeof AuthenticatedPiesIdWydarzenieEntryIdRouteImport
      parentRoute: typeof AuthenticatedPiesIdRoute
    }
    '/_authenticated/pies/$id/wydarzenie/nowe': {
      id: '/_authenticated/pies/$id/wydarzenie/nowe'
      path: '/wydarzenie/nowe'
      fullPath: '/pies/$id/wydarzenie/nowe'
      preLoaderRoute: typeof AuthenticatedPiesIdWydarzenieNoweRouteImport
      parentRoute: typeof AuthenticatedPiesIdRoute
    }
    '/_authenticated/pies/$id/wydarzenie/$entryId/edytuj': {
      id: '/_authenticated/pies/$id/wydarzenie/$entryId/edytuj'
      path: '/edytuj'
      fullPath: '/pies/$id/wydarzenie/$entryId/edytuj'
      preLoaderRoute: typeof AuthenticatedPiesIdWydarzenieEntryIdEdytujRouteImport
      parentRoute: typeof AuthenticatedPiesIdWydarzenieEntryIdRoute
    }
  }
}

interface AuthenticatedPiesIdWydarzenieEntryIdRouteChildren {
  AuthenticatedPiesIdWydarzenieEntryIdEdytujRoute: typeof AuthenticatedPiesIdWydarzenieEntryIdEdytujRoute
}

const AuthenticatedPiesIdWydarzenieEntryIdRouteChildren: AuthenticatedPiesIdWydarzenieEntryIdRouteChildren =
  {
    AuthenticatedPiesIdWydarzenieEntryIdEdytujRoute:
      AuthenticatedPiesIdWydarzenieEntryIdEdytujRoute,
  }

const AuthenticatedPiesIdWydarzenieEntryIdRouteWithChildren =
  AuthenticatedPiesIdWydarzenieEntryIdRoute._addFileChildren(
    AuthenticatedPiesIdWydarzenieEntryIdRouteChildren,
  )

interface AuthenticatedPiesIdRouteChildren {
  AuthenticatedPiesIdAnalizaRoute: typeof AuthenticatedPiesIdAnalizaRoute
  AuthenticatedPiesIdKalendarzRoute: typeof AuthenticatedPiesIdKalendarzRoute
  AuthenticatedPiesIdTabelaRoute: typeof AuthenticatedPiesIdTabelaRoute
  AuthenticatedPiesIdZaleceniaRoute: typeof AuthenticatedPiesIdZaleceniaRoute
  AuthenticatedPiesIdIndexRoute: typeof AuthenticatedPiesIdIndexRoute
  AuthenticatedPiesIdWydarzenieEntryIdRoute: typeof AuthenticatedPiesIdWydarzenieEntryIdRouteWithChildren
  AuthenticatedPiesIdWydarzenieNoweRoute: typeof AuthenticatedPiesIdWydarzenieNoweRoute
}

const AuthenticatedPiesIdRouteChildren: AuthenticatedPiesIdRouteChildren = {
  AuthenticatedPiesIdAnalizaRoute: AuthenticatedPiesIdAnalizaRoute,
  AuthenticatedPiesIdKalendarzRoute: AuthenticatedPiesIdKalendarzRoute,
  AuthenticatedPiesIdTabelaRoute: AuthenticatedPiesIdTabelaRoute,
  AuthenticatedPiesIdZaleceniaRoute: AuthenticatedPiesIdZaleceniaRoute,
  AuthenticatedPiesIdIndexRoute: AuthenticatedPiesIdIndexRoute,
  AuthenticatedPiesIdWydarzenieEntryIdRoute:
    AuthenticatedPiesIdWydarzenieEntryIdRouteWithChildren,
  AuthenticatedPiesIdWydarzenieNoweRoute:
    AuthenticatedPiesIdWydarzenieNoweRoute,
}

const AuthenticatedPiesIdRouteWithChildren =
  AuthenticatedPiesIdRoute._addFileChildren(AuthenticatedPiesIdRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedPsyRoute: typeof AuthenticatedPsyRoute
  AuthenticatedPiesIdRoute: typeof AuthenticatedPiesIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedPsyRoute: AuthenticatedPsyRoute,
  AuthenticatedPiesIdRoute: AuthenticatedPiesIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  KontaktRoute: KontaktRoute,
  PrywatnoscRoute: PrywatnoscRoute,
  RegulaminRoute: RegulaminRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
